### ISSUE TITLE
Where does 50% clustering happen in uniclust_workflow.sh?

### ISSUE THREAD

**Issue by gjoni** [soedinglab/uniclust-pipeline#2]
I have some difficulties in figuring out how the 50% clustering takes place in the uniclust_workflow.sh file. '--min-seq-id' parameter is either 0.9 or 0.3 in lines 35-37. Are these thresholds relevant?

**Comment by milot-mirdita** [comment]
```
# cluster down to 50% 
mmseqs filterdb "$TMPPATH/aln_step$STEP" "$TMPPATH/aln_uniclust50" \
    --filter-column 3 --filter-regex '(0\.[5-9][0-9]{2}|1\.000)'
mmseqs clust $INPUT "$TMPPATH/aln_uniclust50" "$TMPPATH/clu_uniclust50" ${CLUSTER2_PAR}
```

Here. 

We use the 30% alignment results and filter out everything under 50% and cluster afterwards. This is computationally somewhat inefficient (compared to the normal cascaded clustering), but we found this resulted in slightly better clustering quality than the direct approach.

Best regards,
Milot

**Comment by gjoni** [comment]
Thanks a lot, Milot!
