### ISSUE TITLE
Link to uniclust annotation not working

### ISSUE THREAD

**Issue by chrismacdermaid** [soedinglab/uniclust-pipeline#4]
Hi Folks,
The link to the uniclust_2017_10_annotation archive is not working. Could you please double check this?  

http://gwdu111.gwdg.de/~compbiol/uniclust/2017_10/uniclust_2017_10_annotation.tar.gz

Thanks

**Comment by milot-mirdita** [comment]
Sorry, the permissions for the file were wrong. Fixed it, thank you!

**Comment by chrismacdermaid** [comment]
Beautiful. Thank you.
