### ISSUE TITLE
missing uniclust '_hhsuite' for 2016_03

### ISSUE THREAD

**Issue by danpf** [soedinglab/uniclust-pipeline#7]
hello,
Is it intentional that http://wwwuser.gwdg.de/~compbiol/uniclust/2016_03/ has no '_hhsuite' file?
thanks in advance!

**Comment by milot-mirdita** [comment]
Sorry for the late answer. We had discovered a while ago that the 2016_03 hh-suite database had a small issue. We removed the release since recomputing it would not have been worth it after we had already computed a new release (the process takes quite some time and a lot of our cluster capacity).
